"""
Custom blocks auto-generated by the Gelochip corrector agent.

Each file in this directory is a manually-implemented GLayout cell that was
created when a required building block was missing from core.cells.*.

Usage in layout code:
    from core.custom_blocks.my_block import my_block

These blocks are auto-discovered by list_available_blocks() tool.
"""
from __future__ import annotations
import importlib
from pathlib import Path

_HERE = Path(__file__).parent

def _load_all() -> dict:
    """Dynamically import all custom block modules."""
    blocks = {}
    for py_file in sorted(_HERE.glob("*.py")):
        if py_file.name.startswith("_"):
            continue
        mod_name = py_file.stem
        try:
            mod = importlib.import_module(f"core.custom_blocks.{mod_name}")
            if hasattr(mod, mod_name):
                blocks[mod_name] = getattr(mod, mod_name)
        except Exception:
            pass
    return blocks
